2021-10-31 10:33:11,330 INFO    MainThread:569 [wandb_setup.py:_flush():71] setting env: {}
2021-10-31 10:33:11,330 INFO    MainThread:569 [wandb_setup.py:_flush():71] setting login settings: {}
2021-10-31 10:33:11,330 INFO    MainThread:569 [wandb_setup.py:_flush():71] setting login settings: {}
2021-10-31 10:33:11,330 INFO    MainThread:569 [wandb_init.py:_log_setup():357] Logging user logs to /home/ubuntu/w251-hw9/slave/wandb/run-20211031_103311-285ki779/logs/debug.log
2021-10-31 10:33:11,331 INFO    MainThread:569 [wandb_init.py:_log_setup():358] Logging internal logs to /home/ubuntu/w251-hw9/slave/wandb/run-20211031_103311-285ki779/logs/debug-internal.log
2021-10-31 10:33:11,331 INFO    MainThread:569 [wandb_init.py:_jupyter_setup():307] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f0138625520>
2021-10-31 10:33:11,332 INFO    MainThread:569 [wandb_init.py:init():390] calling init triggers
2021-10-31 10:33:11,332 INFO    MainThread:569 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {}
2021-10-31 10:33:11,332 INFO    MainThread:569 [wandb_init.py:init():435] starting backend
2021-10-31 10:33:11,332 INFO    MainThread:569 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-10-31 10:33:11,353 INFO    MainThread:569 [backend.py:ensure_launched():199] starting backend process...
2021-10-31 10:33:11,358 INFO    MainThread:569 [backend.py:ensure_launched():204] started backend process with pid: 603
2021-10-31 10:33:11,359 INFO    MainThread:569 [wandb_init.py:init():444] backend started and connected
2021-10-31 10:33:11,361 INFO    MainThread:569 [wandb_run.py:_label_probe_notebook():866] probe notebook
2021-10-31 10:33:11,361 INFO    MainThread:569 [wandb_run.py:_label_probe_notebook():876] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-10-31 10:33:11,361 INFO    MainThread:569 [wandb_init.py:init():503] updated telemetry
2021-10-31 10:33:11,370 INFO    MainThread:569 [wandb_init.py:init():533] communicating current version
2021-10-31 10:33:12,073 INFO    MainThread:569 [wandb_init.py:init():538] got version response 
2021-10-31 10:33:12,074 INFO    MainThread:569 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2021-10-31 10:33:12,160 INFO    MainThread:569 [wandb_init.py:init():576] starting run threads in backend
2021-10-31 10:33:12,671 INFO    MainThread:569 [wandb_run.py:_console_start():1693] atexit reg
2021-10-31 10:33:12,672 INFO    MainThread:569 [wandb_run.py:_redirect():1567] redirect: SettingsConsole.WRAP
2021-10-31 10:33:12,672 INFO    MainThread:569 [wandb_run.py:_redirect():1604] Wrapping output streams.
2021-10-31 10:33:12,673 INFO    MainThread:569 [wandb_run.py:_redirect():1628] Redirects installed.
2021-10-31 10:33:12,673 INFO    MainThread:569 [wandb_init.py:init():603] run started, returning control to user process
2021-10-31 10:33:12,675 INFO    MainThread:569 [wandb_init.py:_pause_backend():270] pausing backend
2021-10-31 10:33:12,675 INFO    MainThread:569 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-10-31 10:33:12,886 INFO    MainThread:569 [wandb_init.py:_resume_backend():279] resuming backend
2021-10-31 10:33:12,888 INFO    MainThread:569 [wandb_init.py:_pause_backend():270] pausing backend
2021-10-31 10:33:12,888 INFO    MainThread:569 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-10-31 10:33:14,623 INFO    MainThread:569 [wandb_init.py:_resume_backend():279] resuming backend
2021-10-31 10:33:14,671 INFO    MainThread:569 [wandb_init.py:_pause_backend():270] pausing backend
2021-10-31 10:33:14,672 INFO    MainThread:569 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-10-31 10:33:16,525 INFO    MainThread:569 [wandb_init.py:_resume_backend():279] resuming backend
2021-10-31 10:33:16,526 INFO    MainThread:569 [wandb_init.py:_pause_backend():270] pausing backend
2021-10-31 10:33:16,526 INFO    MainThread:569 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-10-31 10:33:17,035 INFO    MainThread:569 [wandb_init.py:_resume_backend():279] resuming backend
2021-10-31 10:33:17,036 INFO    MainThread:569 [wandb_init.py:_pause_backend():270] pausing backend
2021-10-31 10:33:17,036 INFO    MainThread:569 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-10-31 10:33:18,703 INFO    MainThread:569 [wandb_init.py:_resume_backend():279] resuming backend
2021-10-31 10:33:18,704 INFO    MainThread:569 [wandb_init.py:_pause_backend():270] pausing backend
2021-10-31 10:33:18,704 INFO    MainThread:569 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-10-31 10:33:19,442 INFO    MainThread:569 [wandb_init.py:_resume_backend():279] resuming backend
2021-10-31 10:33:19,451 INFO    MainThread:569 [wandb_setup.py:_flush():71] setting env: {}
2021-10-31 10:33:19,451 INFO    MainThread:569 [wandb_setup.py:_flush():71] setting login settings: {}
2021-10-31 10:33:19,451 INFO    MainThread:569 [wandb_setup.py:_flush():71] setting login settings: {}
2021-10-31 10:33:19,452 INFO    MainThread:569 [wandb_init.py:_log_setup():357] Logging user logs to /home/ubuntu/w251-hw9/slave/wandb/run-20211031_103319-2siffccy/logs/debug.log
2021-10-31 10:33:19,452 INFO    MainThread:569 [wandb_init.py:_log_setup():358] Logging internal logs to /home/ubuntu/w251-hw9/slave/wandb/run-20211031_103319-2siffccy/logs/debug-internal.log
2021-10-31 10:33:19,452 INFO    MainThread:569 [wandb_init.py:init():390] calling init triggers
2021-10-31 10:33:19,452 INFO    MainThread:569 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {'epochs': 2, 'batch_size': 500, 'momentum': 0.9, 'WEIGHT_DECAY': 0.0001, 'arch': 'resnet18'}
2021-10-31 10:33:19,452 INFO    MainThread:569 [wandb_init.py:init():410] re-initializing run, found existing run on stack: 285ki779
2021-10-31 10:33:19,453 INFO    MainThread:569 [wandb_run.py:finish():1347] finishing run rochelleli/w251-hw9/285ki779
2021-10-31 10:33:19,453 INFO    MainThread:569 [jupyter.py:save_history():429] not saving jupyter history
2021-10-31 10:33:19,453 INFO    MainThread:569 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-10-31 10:33:19,453 INFO    MainThread:569 [wandb_init.py:_jupyter_teardown():289] cleaning up jupyter logic
2021-10-31 10:33:19,453 INFO    MainThread:569 [wandb_run.py:_atexit_cleanup():1663] got exitcode: 0
2021-10-31 10:33:19,454 INFO    MainThread:569 [wandb_run.py:_restore():1635] restore
2021-10-31 10:33:20,185 INFO    MainThread:569 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 781
  total_bytes: 781
}

2021-10-31 10:33:20,332 INFO    MainThread:569 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 781
  total_bytes: 781
}

2021-10-31 10:33:21,170 INFO    MainThread:569 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 781
  total_bytes: 4827
}

2021-10-31 10:33:21,271 INFO    MainThread:569 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 5152
  total_bytes: 5152
}

2021-10-31 10:33:21,372 INFO    MainThread:569 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 5152
  total_bytes: 5152
}

2021-10-31 10:33:21,473 INFO    MainThread:569 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 5152
  total_bytes: 5152
}

2021-10-31 10:33:21,574 INFO    MainThread:569 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 5152
  total_bytes: 5152
}

2021-10-31 10:33:21,675 INFO    MainThread:569 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 5152
  total_bytes: 5152
}

2021-10-31 10:33:21,852 INFO    MainThread:569 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 5152
  total_bytes: 5152
}

2021-10-31 10:33:22,054 INFO    MainThread:569 [wandb_run.py:_wait_for_finish():1793] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 5152
  total_bytes: 5152
}
local_info {
}

2021-10-31 10:33:23,154 INFO    MainThread:569 [wandb_run.py:_append_files():2061] logging synced files
